refactor: rename function name
rename `FOOln` to `FOO_ln`

diff --git a/app/dk b/app/dk
--- a/app/dk
+++ b/app/dk
@@ -33,11 +33,11 @@ if [ ! -f "${dk_containers_file}" ]; then
   echo "" >"${dk_containers_file}"
 fi
 
-function errorln() {
+function error_ln() {
   printf "\033[1;32;31m%s\n\033[m" "$1"
 }
 
-function warningln() {
+function warning_ln() {
   printf "\033[1;33m%s\n\033[m" "$1"
 }
 
@@ -75,7 +75,7 @@ EOF
 }
 
 if [ -z "$(command -v docker)" ]; then
-  errorln "Error: 'docker' required but not found" >&2
+  error_ln "Error: 'docker' required but not found" >&2
   show_usage >&2
   exit 1
 fi
@@ -142,7 +142,7 @@ while (($#)); do
 
   *)
     docker_replace_dk=""
-    warningln "Warning: Unsupported option: '$1'"
+    warning_ln "Warning: Unsupported option: '$1'"
     printf "replace 'dk' with 'docker' ? [Y/n] "
     read -r docker_replace_dk
     if echo "${docker_replace_dk}" | grep -q -E "n|no|N|No|NO"; then
diff --git a/tools/dk-run b/tools/dk-run
--- a/tools/dk-run
+++ b/tools/dk-run
@@ -24,11 +24,11 @@ dk_home="$(dirname "$(dirname "$(realpath "$0")")")"
 dk_data_home="${dk_home}/dk-data"
 dk_containers_file="${dk_data_home}"/containers.txt
 
-function errorln() {
+function error_ln() {
   printf "\033[1;32;31m%s\n\033[m" "$1"
 }
 
-function warningln() {
+function warning_ln() {
   printf "\033[1;33m%s\n\033[m" "$1"
 }
 
@@ -110,13 +110,13 @@ while (($#)); do
 
   --gpus)
     if [ -z "$2" ]; then
-      errorln "Error: '$1' requires a non empty argument" >&2
+      error_ln "Error: '$1' requires a non empty argument" >&2
       show_usage >&2
       exit 1
     fi
     # check if nvidia-docker exists
     if [ -z "$(command -v nvidia-docker)" ]; then
-      errorln "Error: 'nvidia-docker' required but not found" >&2
+      error_ln "Error: 'nvidia-docker' required but not found" >&2
       show_usage >&2
       exit 1
     fi
@@ -131,7 +131,7 @@ while (($#)); do
 
   --name)
     if [ -z "$2" ]; then
-      errorln "Error: '$1' requires a non empty argument" >&2
+      error_ln "Error: '$1' requires a non empty argument" >&2
       show_usage >&2
       exit 1
     fi
@@ -144,18 +144,18 @@ while (($#)); do
 
   --other-flags)
     if [ -z "$2" ]; then
-      errorln "Error: '$1' requires a non empty argument" >&2
+      error_ln "Error: '$1' requires a non empty argument" >&2
       show_usage >&2
       exit 1
     fi
     DOCKER_FLAGS+=("$2") # assign to DOCKER_FLAGS
-    warningln "Warning: deprecated option: '--other-flags'"
+    warning_ln "Warning: deprecated option: '--other-flags'"
     shift 2
     ;;
 
   -p | --publish)
     if [ -z "$2" ]; then
-      errorln "Error: '$1' requires a non empty argument" >&2
+      error_ln "Error: '$1' requires a non empty argument" >&2
       show_usage >&2
       exit 1
     fi
@@ -165,7 +165,7 @@ while (($#)); do
 
   -v | --volume)
     if [ -z "$2" ]; then
-      errorln "Error: '$1' requires a non empty argument" >&2
+      error_ln "Error: '$1' requires a non empty argument" >&2
       show_usage >&2
       exit 1
     fi
@@ -182,7 +182,7 @@ while (($#)); do
     ;;
 
   --* | -*)
-    errorln "Error: Unknown flag: '$1'" >&2
+    error_ln "Error: Unknown flag: '$1'" >&2
     show_usage >&2
     exit 1
     ;;
@@ -198,7 +198,7 @@ while (($#)); do
         tag="latest"
       fi
       if [ -z "$(docker images -q "${repo}:${tag}")" ]; then
-        errorln "Error: No such docker image: '${repo}:${tag}'" >&2
+        error_ln "Error: No such docker image: '${repo}:${tag}'" >&2
         show_usage >&2
         exit 1
       fi
@@ -219,7 +219,7 @@ while (($#)); do
 done
 
 if [ -z "${image}" ]; then
-  errorln "Error: Missing IMAGE" >&2
+  error_ln "Error: Missing IMAGE" >&2
   show_usage >&2
   exit 1
 fi
diff --git a/tools/dk-update b/tools/dk-update
--- a/tools/dk-update
+++ b/tools/dk-update
@@ -20,11 +20,11 @@
 
 set -euo pipefail
 
-function errorln() {
+function error_ln() {
   printf "\033[1;32;31m%s\n\033[m" "$1"
 }
 
-function infoln() {
+function info_ln() {
   printf "\033[0;32;32m%s\n\033[m" "$1"
 }
 
@@ -56,7 +56,7 @@ while (($#)); do
     ;;
 
   --* | -* | *)
-    errorln "Error: Unknown flag: '$1'" >&2
+    error_ln "Error: Unknown flag: '$1'" >&2
     show_usage >&2
     exit 1
     ;;
@@ -64,29 +64,29 @@ while (($#)); do
 done
 
 if [ -z "$(command -v curl)" ]; then
-  errorln "Error: 'curl' required but not found" >&2
+  error_ln "Error: 'curl' required but not found" >&2
   show_usage >&2
   exit 1
 fi
 
 latest_tag="$(get_latest_tag duruyao/DockDuck)"
 if [ -z "${latest_tag}" ]; then
-  errorln "Error: Latest tag required but not found, please check your network" >&2
+  error_ln "Error: Latest tag required but not found, please check your network" >&2
   show_usage >&2
   exit 1
 fi
-infoln "Detected latest tag: '${latest_tag}'"
+info_ln "Detected latest tag: '${latest_tag}'"
 
 url="https://github.com/duruyao/DockDuck/archive/refs/tags/${latest_tag}.tar.gz"
 latest_release=${latest_tag//v/}
 
 if [ -z "$(command -v tar)" ]; then
-  errorln "Error: 'tar' required but not found" >&2
+  error_ln "Error: 'tar' required but not found" >&2
   show_usage >&2
   exit 1
 fi
 if [ -z "$(command -v gzip)" ]; then
-  errorln "Error: 'gzip' required but not found" >&2
+  error_ln "Error: 'gzip' required but not found" >&2
   show_usage >&2
   exit 1
 fi
@@ -94,12 +94,12 @@ fi
 tmp_dir="/tmp/$(date | md5sum | head -c 10)"
 mkdir -p "${tmp_dir}"
 pushd "${tmp_dir}" 1>/dev/null
-infoln "Downloading package from ${url} ..."
+info_ln "Downloading package from ${url} ..."
 curl -LSso DockDuck-"${latest_release}".tar.gz "${url}"
 tar -zxvf DockDuck-"${latest_release}".tar.gz 1>/dev/null
 pushd DockDuck-"${latest_release}" 1>/dev/null
 if [ "NOTFOUND" == "${DK_HOME-NOTFOUND}" ]; then
-  warningln "Warning: \$DK_HOME not found, use default '$USER/.duck'"
+  warning_ln "Warning: \$DK_HOME not found, use default '$USER/.duck'"
   bash install.sh
 else
   bash install.sh --prefix "${DK_HOME}"
