feat: use docker instead of dk when passing unsupported options

diff --git a/app/dk b/app/dk
--- a/app/dk
+++ b/app/dk
@@ -37,9 +37,13 @@ function errorln() {
   printf "\033[1;32;31m%s\n\033[m" "${1}"
 }
 
+function warningln() {
+  printf "\033[1;33m%s\n\033[m" "${1}"
+}
+
 function show_version() {
   cat <<EOF
-DockDucK v2022.03.22
+DockDucK v2022.03.27-pre
 EOF
 }
 
@@ -48,7 +52,7 @@ function show_usage() {
   cat <<EOF
 Usage: dk [OPTIONS] [COMMAND]
 
-A shortcut for using dock-duck containers
+Tools for using dock-duck containers
 
 Options:
   -h, --help                    Display this help message
@@ -70,7 +74,7 @@ EOF
 }
 
 if [ -z "$(command -v docker)" ]; then
-  errorln "Error: Command 'docker' not found, try: sudo apt install <deb name>" >&2
+  errorln "Error: 'docker' required but not found" >&2
   show_usage >&2
   exit 1
 fi
@@ -129,10 +133,19 @@ while (($#)); do
     exit 0
     ;;
 
-  --* | -* | *)
-    errorln "Error: Unknown flag: $1" >&2
-    show_usage >&2
-    exit 1
+  *)
+    docker_replace_dk=""
+    warningln "Warning: Unsupported option: '$1'"
+    printf "replace 'dk' with 'docker' ? [Y/n] "
+    read -r docker_replace_dk
+    if echo "${docker_replace_dk}" | grep -q -E "n|no|N|No|NO"; then
+      show_usage >&2
+      exit 1
+    else
+      shift 1
+      docker "$@"
+      exit 0
+    fi
     ;;
   esac
 done
