refactor: move codes of making 'DK_HOME' and checking if docker exists to 'apps/dk'

diff --git a/apps/dk b/apps/dk
--- a/apps/dk
+++ b/apps/dk
@@ -40,6 +40,17 @@ See more about DockDucK at https://github.com/duruyao/DockDucK
 EOF
 }
 
+dk_home="${HOME}"/.DockDuck
+dk_containers_file="${dk_home}"/containers.txt
+mkdir -p "${dk_home}"
+printf "" >>"${dk_containers_file}"
+
+if [ -z "$(command -v docker)" ]; then
+  errorln "Error: Command 'docker' not found, try: sudo apt install <deb name>" >&2
+  show_usage >&2
+  exit 1
+fi
+
 if [ 0 == $# ]; then
   show_usage
   exit 0
